apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-1-pv-claim
spec:
  storageClassName: node-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-2-pv-claim
spec:
  storageClassName: node-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-3-pv-claim
spec:
  storageClassName: node-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-4-pv-claim
spec:
  storageClassName: node-4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-5-pv-claim
spec:
  storageClassName: node-5
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
